#!/bin/sh

AUGTOOL=/usr/bin/augtool
SED=/bin/sed

position=`$AUGTOOL print /files/etc/grub.conf | grep $1 | awk -F[ '{print $2}' | awk -F] '{print $1}'`
if [  $position > 0 ]; then
	new_position=`expr $position - 1`
	unlink /tmp/tmpfile.$$
        $SED -e "s/default=$position/default=$new_position/g" /etc/grub.conf > /tmp/tmpfile.$$
        cp /tmp/tmpfile.$$ /etc/grub.conf
        rm /tmp/tmpfile.$$
fi ;
