#!/bin/sh
# Startup script for mysqld (gmm)
#
# chkconfig: 2345 55 25
# description: Startup script for the GMM mysqld instance

# Source function library.
. /etc/rc.d/init.d/functions

[ -f /etc/snmp/monitorCPU.sh ] || exit 0

prog="CPU Monitoring"

case "$1" in
        start)
            echo -n $"Starting $prog: "
            mypid=`ps -C monitorCPU.sh --no-headers -o pid | sed "s/ //g"`
            if [ $mypid ]
            then
               exit 0 
            else    
               /etc/snmp/monitorCPU.sh&            
            fi
            ;;

        stop)
            echo -n $"Stopping $prog: "            
            mypid=`ps -C monitorCPU.sh --no-headers -o pid | sed "s/ //g"`		
		
			# if the mypid is not null
			if [ $mypid ]
			then									
				kill -9 $mypid
			fi	
            ;;
        *)
            echo $"Usage: $0 {start|stop}"
            exit 1

esac

exit $RETVAL
